name: CI

on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ test-ci ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PS3 SDK
        run: |
          Invoke-WebRequest -Uri "https://github.com/itacentury/T5GSCLoader/releases/download/ps3sdk/ps3sdk.zip" -OutFile ps3sdk.zip
          Expand-Archive ps3sdk.zip -DestinationPath D:\ps3sdk
          setx SCE_PS3_ROOT "D:\ps3sdk"

      - name: Set PS3 SDK in PATH
        shell: pwsh
        run: |
          $root = 'D:\ps3sdk'
    
          # 1) SCE_PS3_ROOT braucht sdk.makedef.mk
          Write-Output "SCE_PS3_ROOT=$root" >> $Env:GITHUB_ENV
          # 2) PS3DEV braucht sdk.target.mk für den Compiler‑Pfad
          Write-Output "PS3DEV=$root"       >> $Env:GITHUB_ENV
    
          # 3) Wenn Ihr es trotzdem über den PATH gewohnt seid:
          $dirs = 'host-win32\ppu\bin','host-win32\spu\bin','host-win32\sn\bin','host-win32\CG\bin'
          $prefix = ($dirs | ForEach-Object { Join-Path $root $_ }) -join ';'
          Write-Output "PATH=$prefix;$Env:PATH" >> $Env:GITHUB_ENV

      - name: Build project
        shell: bash
        env:
          PS3DEV:       "/d/ps3sdk"   # <-- Unix‑Mount unter Bash
          SCE_PS3_ROOT: "/d/ps3sdk"   # <- falls sdk.makedef.mk das auch braucht
        run: |
          # optional: Path ergänzen, wenn Ihr über PATH starten wollt
          export PATH="$PS3DEV/host-win32/ppu/bin:$PS3DEV/host-win32/spu/bin:$PS3DEV/host-win32/sn/bin:$PS3DEV/host-win32/CG/bin:$PATH"

          # Debug: zeigt Dir, ob das Verzeichnis wirklich da ist
          ls -l /d/ps3sdk/host-win32/ppu/bin/ppu-lv2-gcc

          cd "$GITHUB_WORKSPACE"
          make

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
              reports/
              bin/debug/*.xml
