name: CI

on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ test-ci ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PS3 SDK
        run: |
          Invoke-WebRequest -Uri "https://github.com/itacentury/T5GSCLoader/releases/download/ps3sdk/PS3SDK.zip" -OutFile ps3sdk.zip
          Expand-Archive ps3sdk.zip -DestinationPath C:\ps3sdk
          setx PS3SDK_ROOT "C:\ps3sdk"

      - name: Build project
        run: |
          cd $env:GITHUB_WORKSPACE
          make all

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
              reports/
              bin/debug/*.xml
