name: CI

on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ test-ci ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PS3 SDK
        run: |
          Invoke-WebRequest -Uri "https://github.com/itacentury/T5GSCLoader/releases/download/ps3sdk/ps3sdk.zip" -OutFile ps3sdk.zip
          Expand-Archive ps3sdk.zip -DestinationPath D:\ps3sdk
          setx SCE_PS3_ROOT "D:\ps3sdk"

    #   - name: Set PS3 SDK in PATH
    #     shell: pwsh
    #     run: |
    #       $sdkRoot = "D:\ps3sdk"
    #       $dirs = "host-win32\ppu\bin","host-win32\spu\bin","host-win32\sn\bin","host-win32\CG\bin"
    #       $prefix = ($dirs | ForEach-Object { "$sdkRoot/$_" }) -join ";"
    #       Write-Output "PATH=$prefix;${env:PATH}" >> $Env:GITHUB_ENV
    #       Write-Output "SCE_PS3_ROOT=D:\ps3sdk" >> $Env:GITHUB_ENV

      - name: Build project
        shell: bash
        env:
          SCE_PS3_ROOT: /d/ps3sdk
        run: |
          export PATH="$SCE_PS3_ROOT/host-win32/ppu/bin:$SCE_PS3_ROOT/host-win32/spu/bin:$SCE_PS3_ROOT/host-win32/sn/bin:$SCE_PS3_ROOT/host-win32/CG/bin:$PATH"
          cd "$GITHUB_WORKSPACE"
          make

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
              reports/
              bin/debug/*.xml
